-- set keymaps
local key = require("barney.lib.keymap")
local harpoon = require("harpoon")

harpoon:setup()

key.nmap("<leader>ha", function()
  harpoon:list():add()
end, "[h]arpoon [a]dd")
key.nmap("<leader>hm", function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end, "[h]arpoon [m]enu")
key.nmap("<leader>h1", function()
  harpoon:list():select(1)
end, "[h]arpoon 1")
key.nmap("<leader>h2", function()
  harpoon:list():select(2)
end, "[h]arpoon 2")
key.nmap("<leader>h3", function()
  harpoon:list():select(3)
end, "[h]arpoon 3")
key.nmap("<leader>h4", function()
  harpoon:list():select(4)
end, "[h]arpoon 4")
key.nmap("<leader>h5", function()
  harpoon:list():select(5)
end, "[h]arpoon 5")
